=== CESNET/shongo/sw/shongo/doc/reports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="reports">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jade" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="report" type="jade-report" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="api" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="report" type="api-report" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="scheduler" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="report" type="scheduler-report" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="executor" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="report" type="executor-report" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!--
    -  Common Types
    -->

    <xs:simpleType name="report-module">
        <xs:restriction base="xs:string">
            <xs:enumeration value="common"/>
            <xs:enumeration value="controller"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="severity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="error"/>
            <xs:enumeration value="warn"/>
            <xs:enumeration value="info"/>
            <xs:enumeration value="debug"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="report-param">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="type" type="report-param-type"/>
    </xs:complexType>

    <xs:simpleType name="report-param-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="string"/>
            <xs:enumeration value="jade-report"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="report-user">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="via" type="report-user-via"/>
    </xs:complexType>

    <xs:simpleType name="report-user-via">
        <xs:restriction base="xs:string">
            <xs:enumeration value="email"/>
            <xs:enumeration value="ui"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="report-domain-admin">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="log" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="via" type="report-domain-admin-via"/>
    </xs:complexType>

    <xs:simpleType name="report-domain-admin-via">
        <xs:restriction base="xs:string">
            <xs:enumeration value="email"/>
            <xs:enumeration value="log"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="report-device-admin">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="via" type="report-device-admin-via"/>
    </xs:complexType>

    <xs:simpleType name="report-device-admin-via">
        <xs:restriction base="xs:string">
            <xs:enumeration value="email"/>
        </xs:restriction>
    </xs:simpleType>


    <!--
    -  Jade Report
    -->

    <xs:complexType name="jade-report">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="classification">
                <xs:complexType>
                    <xs:attribute name="severity" type="severity"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="params">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="param" type="report-param" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="example" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


    <!--
      -  API Report
      -->

    <xs:complexType name="api-report">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="classification">
                <xs:complexType>
                    <xs:attribute name="severity" type="severity"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="params">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="param" type="report-param" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="example" type="xs:string"/>
            <xs:element name="user" type="report-user"/>
            <xs:element name="domain-admin" type="report-domain-admin"/>
            <xs:element name="device-admin" type="report-device-admin"/>
        </xs:sequence>
        <xs:attribute name="module" type="report-module"/>
    </xs:complexType>


    <!--
      -  Scheduler Report
      -->

    <xs:complexType name="scheduler-report">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="classification">
                <xs:complexType>
                    <xs:attribute name="severity" type="severity"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="example" type="xs:string"/>
            <xs:element name="user" type="report-user"/>
            <xs:element name="domain-admin" type="report-domain-admin"/>
            <xs:element name="device-admin" type="report-device-admin"/>
        </xs:sequence>
    </xs:complexType>


    <!--
    -  Executor Report
    -->

    <xs:complexType name="executor-report">
        <xs:sequence>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="classification">
                <xs:complexType>
                    <xs:attribute name="severity" type="severity"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="params">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="param" type="report-param" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="example" type="xs:string"/>
            <xs:element name="resolution" type="executor-report-resolution"/>
            <xs:element name="user" type="report-user"/>
            <xs:element name="domain-admin" type="report-domain-admin"/>
            <xs:element name="device-admin" type="report-device-admin"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="executor-report-resolution">
        <xs:restriction base="xs:string">
            <xs:enumeration value="fail"/>
            <xs:enumeration value="try-again"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== CESNET/shongo/sw/shongo/doc/reports.xml
<?xml version="1.0" encoding="UTF-8" ?>

<reports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="reports.xsd">

    <scopes>
        <scope>
            <name>jade</name>
            <module>common-api</module>
            <class-name>cz.cesnet.shongo.JadeReportSet</class-name>
        </scope>

        <scope>
            <name>common</name>
            <module>common-api</module>
            <class-name>cz.cesnet.shongo.CommonReportSet</class-name>
        </scope>

        <scope>
            <name>controller</name>
            <module>controller-api</module>
            <class-name>cz.cesnet.shongo.controller.ControllerReportSet</class-name>
        </scope>

        <!--<scope>
            <name>scheduler</name>
            <module>controller</module>
            <class-name>cz.cesnet.shongo.controller.SchedulerReportSet</class-name>
        </scope>

        <scope>
            <name>executor</name>
            <module>controller</module>
            <class-name>cz.cesnet.shongo.controller.ExecutorReportSet</class-name>
        </scope>-->
    </scopes>

    <!--
        <report abstract="true|false" extends="true|false">
            <persistent></persistent>
            <rpc-api></rpc-api>
            <jade-api></jade-api>
            <id>string</id>
        </report>
    -->

    <scope name="jade">

        <report>
            <id>unknown-error</id>
            <classification severity="error"/>
            <params>
                <param name="description" type="string"/>
            </params>
            <description>
                Unknown error: ${description}
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>agent-not-found</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
            </params>
            <description>
                Receiver agent ${receiver-agent} is not available now.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>agent-not-started</id>
            <classification severity="error"/>
            <params>
                <param name="sender-agent" type="string"/>
            </params>
            <description>
                Server agent ${sender-agent} is not started yet.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-timeout</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
                <param name="command" type="string"/>
            </params>
            <description>
                Command ${command} has timeout.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-not-supported</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
                <param name="command" type="string"/>
            </params>
            <description>
                Receiver agent ${receiver-agent} doesn't implement command ${command}.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-refused</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
                <param name="command" type="string"/>
            </params>
            <description>
                Receiver agent ${receiver-agent} has refused command ${command}.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-not-understood</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
                <param name="command" type="string"/>
            </params>
            <description>
                Receiver agent ${receiver-agent} didn't understand command ${command}.
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-failed</id>
            <classification severity="error"/>
            <params>
                <param name="receiver-agent" type="string"/>
                <param name="command" type="string"/>
                <param name="reason" type="string"/>
            </params>
            <description>
                Receiver agent ${receiver-agent} throws CommandException while processing command ${command}: ${reason}
            </description>
            <example>
                TODO:
            </example>
        </report>

        <report>
            <id>command-result-decoding-failed</id>
            <classification severity="error"/>
            <params>
                <param name="sender-agent" type="string"/>
                <param name="command" type="string"/>
            </params>
            <description>
                Sender agent ${sender-agent} cannot decode response from command ${command}.
            </description>
            <example>
                TODO:
            </example>
        </report>

    </scope>

    <scope name="common">

        <report>
            <id>unknown-error</id>
            <classification severity="error"/>
            <params>
                <param name="description" type="string"/>
            </params>
            <description>
                Unknown error: ${description}
            </description>
            <example>
                TODO:
            </example>
            <user visible="true" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>type-illegal-value</id>
            <classification severity="error"/>
            <params>
                <param name="type" type="string"/>
                <param name="value" type="string"/>
            </params>
            <description>
                Value ${value} is illegal for type ${type}.
            </description>
            <example>
                TODO:
                -Enum
                -Date/Time
                -Period
                -Interval
                -Partial Date/Time
                -DeviceResource.Mode
            </example>
            <user visible="false" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>class-undefined</id>
            <classification severity="error"/>
            <params>
                <param name="class" type="string"/>
            </params>
            <description>
                Class ${class} is not defined.
            </description>
            <example>
                TODO:
            </example>
            <user visible="true" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>class-instantiation-error</id>
            <classification severity="error"/>
            <params>
                <param name="class" type="string"/>
            </params>
            <description>
                Class ${class} cannot be instanced.
            </description>
            <example>
                TODO:
            </example>
            <user visible="true" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>class-attribute-undefined</id>
            <classification severity="error"/>
            <params>
                <param name="class" type="string"/>
                <param name="attribute" type="string"/>
            </params>
            <description>
                Attribute ${attribute} is not defined in class ${class}.
            </description>
            <example>
                TODO:
            </example>
            <user visible="true" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>class-attribute-type-mismatch</id>
            <classification severity="error"/>
            <params>
                <param name="class" type="string"/>
                <param name="attribute" type="string"/>
                <param name="required-type" type="string"/>
                <param name="present-type" type="string"/>
            </params>
            <description>
                Type mismatch of value in attribute ${attribute} in class ${class}.
                Present type ${given-type} doesn't match required type ${required-type}.
            </description>
            <example>
                TODO:
            </example>
            <user visible="true" via="ui">
                <description>TODO:</description>
            </user>
            <domain-admin visible="false"/>
            <device-admin visible="false"/>
        </report>

        <report>
            <id>class-attribute-required</id>
            <classification severity="error"/>
            <params>
                <param name="class" type="string"/>
